# /etc/nixos/modules/home/theme.nix
{ config, pkgs, lib, ... }:

{
  # -------------------------------------------------------------------
  # 🎨 CATPPUCCIN THEME BASE
  # -------------------------------------------------------------------
  catppuccin = {
    enable = true;
    # We default to macchiato, but the toggle script will override specific apps
    flavor = "macchiato";

    # Disable module management for apps we want to toggle dynamically
    # We will manage their config files partly manually (via writable activation)
    helix.enable = false;
    zellij.enable = false;
    alacritty.enable = true; # Alacritty can reload via import file
  };

  # -------------------------------------------------------------------
  # ✨ MUTABLE CONFIGS FOR RUNTIME TOGGLING
  # -------------------------------------------------------------------
  # NixOS normally makes ~/.config files read-only symlinks.
  # To allow 'toggle-theme' to edit them, we must break the symlinks 
  # and copy the files to the user directory during activation.
  home.activation.makeConfigsWritable = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    
    # 1. Helper function
    make_writable() {
      local file="$1"
      local source="$2"
      
      # Only act if the target is a symlink (meaning it's managed by Nix)
      # or if it doesn't exist yet.
      if [ -L "$file" ] || [ ! -f "$file" ]; then
        echo "Making $file writable for theme toggling..."
        mkdir -p "$(dirname "$file")"
        
        # If source exists (from Nix store), copy it. Otherwise create empty/default.
        if [ -f "$source" ]; then
          cp --remove-destination "$(readlink -f "$source" || echo "$source")" "$file"
        else
          # Create default if needed (specific logic below)
          touch "$file"
        fi
        chmod +w "$file"
      fi
    }

    # 2. Make Waybar CSS writable (so we can import theme.css)
    # Note: Waybar is managed by home-manager, so config is usually linked.
    # We rely on the fact that we define the main config in waybar.nix, 
    # but we want the *theme* file to be generated by the script.
    mkdir -p ${config.xdg.configHome}/waybar
    if [ ! -f ${config.xdg.configHome}/waybar/theme.css ]; then
       # Default to Dark on first run
       echo "@define-color base #24273a;" > ${config.xdg.configHome}/waybar/theme.css
    fi

    # 3. Make Hyprland Theme config writable
    mkdir -p ${config.xdg.configHome}/hypr
    if [ ! -f ${config.xdg.configHome}/hypr/theme.conf ]; then
       echo "" > ${config.xdg.configHome}/hypr/theme.conf
    fi

    # 4. Helix Config
    # We let HM generate the file, but then we unlink and copy it
    # so sed can modify the 'theme = ' line.
    # We need to find where HM put the symlink target first.
    HX_PATH="${config.xdg.configHome}/helix/config.toml"
    if [ -L "$HX_PATH" ]; then
       cp --remove-destination "$(readlink "$HX_PATH")" "$HX_PATH"
       chmod +w "$HX_PATH"
    fi

    # 5. Zellij Config
    ZJ_PATH="${config.xdg.configHome}/zellij/config.kdl"
    if [ -L "$ZJ_PATH" ]; then
       cp --remove-destination "$(readlink "$ZJ_PATH")" "$ZJ_PATH"
       chmod +w "$ZJ_PATH"
    fi
  '';

  # -------------------------------------------------------------------
  # ✨ XSESSION & SCALING
  # -------------------------------------------------------------------
  xsession.enable = true;
  xresources.properties = {
    "Xft.dpi" = 192;
    "Xcursor.size" = 48;
  };

  home.sessionVariables = { GDK_SCALE = "2"; QT_SCALE_FACTOR = "2"; };
  gtk.cursorTheme.size = 48;

  # Ensure toggle-theme is installed
  home.packages = [ pkgs.toggle-theme ];
}
